import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ThemeProvider} from "@/components/theme-provider";
import {SessionContextProvider} from "@/components/session-context-provider";
import {getUser} from "@/lib/user";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const user = await getUser();

    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <SessionContextProvider userSession={user}>
                        {children}
                    </SessionContextProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
